# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-01 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20190228_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_ks',
            name='LastPrice',
            field=models.CharField(db_index=True, default=b'N/A', max_length=30),
        ),
    ]
