# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-02 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20190301_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_ks',
            name='LastPrice_v1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
