# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-02 00:36
#This migration is generated using: >python manage.py makemigrations --empty yourappname
#The empty migration is used to populate the new column with data from the old column; this is needed for type change of a column. The "populate_new_col" function goes into the empty "operations".

from __future__ import unicode_literals

from django.db import migrations
from decimal import Decimal

def populate_new_col(apps, schema_editor):  #Plug data from 'LastPrice' into 'LastPrice_v1' in the same model class 'all_ks'.
    all_ks = apps.get_model('blog', 'all_ks')
    for ks in all_ks.objects.all():
        print ks.Day, ks.Symbol, ks.LastPrice
        #if float(ks.LastPrice):  #Check if conversion to float type is possible...
        try:
            #print ks.LastPrice
            #ks.LastPrice_v1, created = all_ks.objects.get_or_create(LastPrice_v1=ks.LastPrice)  #TypeError: Tried to update field blog.All_ks.LastPrice_v1 with a model instance, <All_ks: All_ks object>. Use a value compatible with DecimalField.
            #ks.LastPrice_v1, created = all_ks.objects.get_or_create(LastPrice_v1=Decimal(float(ks.LastPrice)*1.0))  #TypeError: Tried to update field blog.All_ks.LastPrice_v1 with a model instance, <All_ks: All_ks object>. Use a value compatible with DecimalField.
            #Decimal(ks.LastPrice_v1)  #TypeError: Cannot convert <All_ks: All_ks object> to Decimal.
            ks.LastPrice_v1 = float(ks.LastPrice)
        #elif ks.LastPrice == 'N/A' :  #...else insert None.
        except ValueError:
            #ks.LastPrice_v1, created = all_ks.objects.get_or_create(LastPrice_v1=None)
            ks.LastPrice_v1 = None
            #float(ks.LastPrice_v1)
        #ks = all_ks(LastPrice_v1=ks.LastPrice)
        #ks.LastPrice_v1 = all_ks(name=ks.LastPrice)
        ks.save()

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_auto_20190301_1600'),
    ]

    operations = [
        migrations.RunPython(populate_new_col),
    ]
