# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-08 21:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_auto_20190308_1211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='all_ks',
            old_name='LastPrice_v1',
            new_name='LastPrice',
        ),
    ]
