# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-15 06:21
#This migration is generated using: >python manage.py makemigrations --empty yourappname
#The empty migration is used to populate the new column with data from the old column; this is needed for type change of a column. The "populate_new_col" function goes into the empty "operations". MAKE SURE TO ADD THE NEW COLUMN WITH MAKEMIGRATIONS BEFORE DATA MIGRATION.
from __future__ import unicode_literals

from django.db import migrations

def populate_new_col(apps, schema_editor):
    all_ks = apps.get_model('blog', 'all_ks')
    for ks in all_ks.objects.all():
        print ks.Day, ks.Symbol, ks.FiftyTwoWkChg
        try:
            ks.FiftyTwoWkChg_v1 = float(ks.FiftyTwoWkChg)
        except ValueError:
            ks.FiftyTwoWkChg_v1 = None
        ks.save()

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_auto_20190314_2300'),
    ]

    operations = [
        migrations.RunPython(populate_new_col),
    ]
