# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-15 07:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_auto_20190315_0004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='all_ks',
            old_name='FiftyTwoWkChg_v1',
            new_name='FiftyTwoWkChg',
        ),
    ]
