# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-15 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0036_remove_all_ks_fiftytwowkchg_v0'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_ks',
            name='DivYild_v1',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True),
        ),
    ]
