# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-15 22:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0039_auto_20190315_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='all_ks',
            old_name='DivYild_v1',
            new_name='DivYild',
        ),
    ]
