# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-15 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0041_remove_all_ks_divyild_v0'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_ks',
            name='TrailPE_v1',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
    ]
