# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-16 01:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0045_auto_20190315_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='all_ks',
            name='TrailPE_v0',
        ),
    ]
